### ISSUE TITLE
i trying to makerarm 3d printer code but still this error come how to fix it or any more code ?

### ISSUE THREAD

**Issue by rushanthans** [rushanthans/i-trying-to-makerarm-3d-printer-code-but-still-this-error-come-how-to-fix-it-or-any-more-code-#1]
C:\Users\pc1\AppData\Local\Temp\ccsCYIBg.ltrans0.ltrans.o: In function `process_parsed_command()':

ccsCYIBg.ltrans0.o:(.text+0xb78): undefined reference to `inverse_kinematics(float const*)'

ccsCYIBg.ltrans0.o:(.text+0xc4a): undefined reference to `inverse_kinematics(float const*)'

ccsCYIBg.ltrans0.o:(.text+0x379a): undefined reference to `inverse_kinematics(float const*)'

ccsCYIBg.ltrans0.o:(.text+0x3b40): undefined reference to `inverse_kinematics(float const*)'

ccsCYIBg.ltrans0.o:(.text+0x3bea): undefined reference to `inverse_kinematics(float const*)'

C:\Users\pc1\AppData\Local\Temp\ccsCYIBg.ltrans3.ltrans.o:ccsCYIBg.ltrans3.o:(.text+0x52c): more undefined references to `inverse_kinematics(float const*)' follow

C:\Users\pc1\AppData\Local\Temp\ccsCYIBg.ltrans7.ltrans.o: In function `get_cartesian_from_steppers()':

ccsCYIBg.ltrans7.o:(.text+0xa2c): undefined reference to `forward_kinematics_SCARA(float const&, float const&)'

C:\Users\pc1\AppData\Local\Temp\ccsCYIBg.ltrans1.ltrans.o: In function `sync_plan_position_kinematic()':

ccsCYIBg.ltrans1.o:(.text+0x160): undefined reference to `inverse_kinematics(float const*)'

C:\Users\pc1\AppData\Local\Temp\ccsCYIBg.ltrans1.ltrans.o: In function `do_homing_move(AxisEnum, float, float) [clone .lto_priv.43]':

ccsCYIBg.ltrans1.o:(.text+0x278): undefined reference to `inverse_kinematics(float const*)'

C:\Users\pc1\AppData\Local\Temp\ccsCYIBg.ltrans1.ltrans.o: In function `prepare_uninterpolated_move_to_destination(float)':

ccsCYIBg.ltrans1.o:(.text+0x8d4): undefined reference to `inverse_kinematics(float const*)'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

**Comment by rushanthans** [comment]
anyone help me please

**Comment by per1234** [comment]
Please provide more details.
